### ISSUE TITLE
this.props.fetchUser() unresolved function in webstorm (App.js)

### ISSUE THREAD

**Issue by rostgoat** [StephenGrider/FullstackReactCode#29]
```
componentDidMount() {
        this.props.fetchUser();
    }
```

while working though the tutorial, fetchUser() is labelled as undefined in webstorms even when 
`import {fetchUser} from "../actions";`
is declared.

any fixes?

**Comment by eponymz** [comment]
So I started having this same issue in vscode.. I had to define my files as JavaScript React format. Regular javascript formatting was making everything go all wonky..

**Comment by rostgoat** [comment]
could you provide the code you used?

**Comment by eponymz** [comment]
That was an IDE specific setting. Curious, when you started the project in webstorm, did you start it as a blank project? Or did you choose the react product template

**Comment by eponymz** [comment]
I actually moved mine from webstorm to vs code. I'm not quite sure how to define jsx as the file format in webstorm. Since it's still javascript.

**Comment by rostgoat** [comment]
oh gotcha.

Somehow it magically started working now after I imported that `import` statement above. Not exactly sure what the issue was there. `this.props.fetchUser();` is still unresolved but seems to work without errors.

Closing issue.
