### ISSUE TITLE
Application error while first deployment

### ISSUE THREAD

**Issue by morfsys** [StephenGrider/FullstackReactCode#7]
I was following the tutorial. In tut. 14, when I ran `heroku open` a new browser window open with the following screen:
![heroku-app-error](https://user-images.githubusercontent.com/25836296/31046879-78b6d110-a61e-11e7-9ea6-5ff10c0e2c55.png)

This is the screenshot of my console
![heroku-error](https://user-images.githubusercontent.com/25836296/31046882-8347af1e-a61e-11e7-963b-baca5b2b3246.png)

**Comment by Mabloq** [comment]
I have the same issue!! Did you figure it out?

**Comment by Mabloq** [comment]
Ok, I looked at one 2 things. 
1. My node -v and npm -v didn't match my engines settings in package.json ( i think this is your problem)
2. I looked closer at the  my logs and saw that I didn't have my heroku env keys matching correctly with my soruce code keys. (my problem)

**Comment by morfsys** [comment]
You are right. Thank you.
